In [4]:
import numpy as np
A=np.array([[56.0,0.0,4.4,68.0],
           [1.2,104.0,52.0,8.0],
           [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal=A.sum(axis=0) #sum vertically  
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage=100*A/cal.reshape(1,4) #python broadcasting  [1 2 3]+100=[101 102 103]
print(percentage) 

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [12]:
#note on python
import numpy as np
a=np.random.randn(5) 
print(a)

[-0.91510227  0.53464013  1.39573983  0.22553389 -0.24063122]


In [13]:
print(a.shape) #rank1 array should be avoided

(5,)


In [14]:
print(a.T) #dimension(1,5)

[-0.91510227  0.53464013  1.39573983  0.22553389 -0.24063122]


In [15]:
print(np.dot(a,a.T))

3.1801108044732667


In [16]:
a=np.random.randn(5,1)
print(a)

[[ 0.29838936]
 [-0.51420927]
 [-1.95699726]
 [ 0.08217476]
 [-2.43551506]]


In [17]:
print(a.T) #2d

[[ 0.29838936 -0.51420927 -1.95699726  0.08217476 -2.43551506]]


In [19]:
print(np.dot(a,a.T))

[[ 0.08903621 -0.15343458 -0.58394717  0.02452008 -0.72673179]
 [-0.15343458  0.26441117  1.00630613 -0.04225503  1.25236442]
 [-0.58394717  1.00630613  3.82983829 -0.16081579  4.76629631]
 [ 0.02452008 -0.04225503 -0.16081579  0.00675269 -0.20013788]
 [-0.72673179  1.25236442  4.76629631 -0.20013788  5.9317336 ]]
